### ISSUE TITLE
Custom Object Tag By Name Not Working

### ISSUE THREAD

**Issue by kennethllamasares** [Ontraport/SDK-PHP#23]
There seems to be an issue with adding tag by name to a custom object. 
The response says **The tag is now being processed."** but upon checking the custom object record, tags are not reflecting

```
$tagByNameParams = array(
            "objectID" => \OntraportAPI\ObjectType::CUSTOM_OBJECT,
            "ids"      => [10, 9],
            "add_names" => ['Test Tag']
);

$response = $this->client->custom(10003)->addTagByName($tagByNameParams);
```

Am I missing something here?

**Comment by akent-op** [comment]
Hi Kenneth,

Try passing your custom object type ID, 10003, to the $tagByNameParams instead of \OntraportAPI\ObjectType::CUSTOM_OBJECT. That constant actually refers to object type ID 99, which is used to manage the group of custom objects themselves. In the methods overridden in the CustomObjects class, we actually use the object type ID passed in to the constructor to overwrite the objectID parameter in those requests, but addTagByName is actually not overridden and will use the object type ID passed to the method. That change should do the trick, let me know if you run into any more issues.

Best,

Arielle

**Comment by kennethllamasares** [comment]
Hello Arielle,

It's working now. Thank you very much!
