### ISSUE TITLE
Form API question

### ISSUE THREAD

**Issue by nicolasguzca** [Ontraport/SDK-PHP#25]
Hello! Quick question, is it possible to submit to an existing form created on Ontraport using the API?
I ask this since we already have a flow created on existing forms that categorizes leads, adds tags and subscribes to a certain newsletter.

Thank you!

**Comment by akent-op** [comment]
Hi Nicolas,

Thanks for the question! Unfortunately the only functionality for forms that our API currently supports is retrieval. I can keep you posted if that changes in the future. Let me know if I can help with anything else.

Best,

Arielle

**Comment by nicolasguzca** [comment]
Hi Arielle! Thank you for your answer, is it possible to maybe start this flow when I create a Contact or Object? 

Thanks

**Comment by akent-op** [comment]
Hey Nicolas,

You could set up a rule in the account so that when a contact is created (or custom object) event occurs, you can check them against conditions and perform any number of actions on them, including tagging, etc. You can create rules via the SDK if it needs to be done in multiple accounts, or just through the UI if you prefer. Does this suit your usecase?

Arielle

**Comment by nicolasguzca** [comment]
I think this will work perfectly. Thanks for all the help! 

Closing this issue.
